spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false #关闭缓存
logging:
  level:
    root: info
    com.qf304.blog: debug
  file: log/blog-dev.log
server:
  port: 8088


